/*******************************************************************************
 * Copyright 2014 KU Leuven Research and Developement - iMinds - Distrinet 
 * 
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 *    Administrative Contact: dnet-project-office@cs.kuleuven.be
 *    Technical Contact: maarten.decat@cs.kuleuven.be
 *    Author: maarten.decat@cs.kuleuven.be
 ******************************************************************************/
package puma.sp.authentication.clients;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "AttributeForwardImplService", targetNamespace = "http://services.proxy.puma/", wsdlLocation = "http://localhost:8080/PUMA-Proxy/AttributeForwardService?wsdl")
public class AttributeForwardImplService
    extends Service
{

    private final static URL ATTRIBUTEFORWARDIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ATTRIBUTEFORWARDIMPLSERVICE_EXCEPTION;
    private final static QName ATTRIBUTEFORWARDIMPLSERVICE_QNAME = new QName("http://services.proxy.puma/", "AttributeForwardImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PUMA-Proxy/AttributeForwardService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ATTRIBUTEFORWARDIMPLSERVICE_WSDL_LOCATION = url;
        ATTRIBUTEFORWARDIMPLSERVICE_EXCEPTION = e;
    }

    public AttributeForwardImplService() {
        super(__getWsdlLocation(), ATTRIBUTEFORWARDIMPLSERVICE_QNAME);
    }

    public AttributeForwardImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AttributeForwardService
     */
    @WebEndpoint(name = "AttributeForwardImplPort")
    public AttributeForwardService getAttributeForwardImplPort() {
        return super.getPort(new QName("http://services.proxy.puma/", "AttributeForwardImplPort"), AttributeForwardService.class);
    }

    private static URL __getWsdlLocation() {
        if (ATTRIBUTEFORWARDIMPLSERVICE_EXCEPTION!= null) {
            throw ATTRIBUTEFORWARDIMPLSERVICE_EXCEPTION;
        }
        return ATTRIBUTEFORWARDIMPLSERVICE_WSDL_LOCATION;
    }

}
